services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: college
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "8080:8080"